# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\BiometricACS\BiometricACS\APP\UI\WindowCreateAccountPanel.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wCreateAccountPanel(object):
    def setupUi(self, wCreateAccountPanel):
        wCreateAccountPanel.setObjectName("wCreateAccountPanel")
        wCreateAccountPanel.resize(366, 256)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wCreateAccountPanel.sizePolicy().hasHeightForWidth())
        wCreateAccountPanel.setSizePolicy(sizePolicy)
        wCreateAccountPanel.setMaximumSize(QtCore.QSize(400, 300))
        self.gridLayout = QtWidgets.QGridLayout(wCreateAccountPanel)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(wCreateAccountPanel)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.tbUsername = QtWidgets.QLineEdit(wCreateAccountPanel)
        self.tbUsername.setObjectName("tbUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tbUsername)
        self.lblRole = QtWidgets.QLabel(wCreateAccountPanel)
        self.lblRole.setObjectName("lblRole")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblRole)
        self.cmbRole = QtWidgets.QComboBox(wCreateAccountPanel)
        self.cmbRole.setObjectName("cmbRole")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbRole)
        self.lblPassword = QtWidgets.QLabel(wCreateAccountPanel)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblPassword)
        self.tbPassword = QtWidgets.QLineEdit(wCreateAccountPanel)
        self.tbPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tbPassword.setObjectName("tbPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tbPassword)
        self.lblConfirmPassword = QtWidgets.QLabel(wCreateAccountPanel)
        self.lblConfirmPassword.setObjectName("lblConfirmPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblConfirmPassword)
        self.tbConfirmPassword = QtWidgets.QLineEdit(wCreateAccountPanel)
        self.tbConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tbConfirmPassword.setObjectName("tbConfirmPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tbConfirmPassword)
        self.lblUsername = QtWidgets.QLabel(wCreateAccountPanel)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblUsername)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnCreate = QtWidgets.QPushButton(wCreateAccountPanel)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout.addWidget(self.btnCreate)
        self.btnCancel = QtWidgets.QPushButton(wCreateAccountPanel)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(wCreateAccountPanel)
        QtCore.QMetaObject.connectSlotsByName(wCreateAccountPanel)

    def retranslateUi(self, wCreateAccountPanel):
        _translate = QtCore.QCoreApplication.translate
        wCreateAccountPanel.setWindowTitle(_translate("wCreateAccountPanel", "BACS Create Account"))
        self.lblTitle.setText(_translate("wCreateAccountPanel", "Create account"))
        self.lblRole.setText(_translate("wCreateAccountPanel", "Role:"))
        self.lblPassword.setText(_translate("wCreateAccountPanel", "Password"))
        self.lblConfirmPassword.setText(_translate("wCreateAccountPanel", "Confirm password:"))
        self.lblUsername.setText(_translate("wCreateAccountPanel", "Username:"))
        self.btnCreate.setText(_translate("wCreateAccountPanel", "Create"))
        self.btnCancel.setText(_translate("wCreateAccountPanel", "Cancel"))

