# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\BiometricACS\BiometricACS\APP\UI\WindowSettingsPanel.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WindowSettingsPanel(object):
    def setupUi(self, WindowSettingsPanel):
        WindowSettingsPanel.setObjectName("WindowSettingsPanel")
        WindowSettingsPanel.setWindowModality(QtCore.Qt.WindowModal)
        WindowSettingsPanel.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(WindowSettingsPanel)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.lblSettingsFile = QtWidgets.QLabel(WindowSettingsPanel)
        self.lblSettingsFile.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSettingsFile.setObjectName("lblSettingsFile")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblSettingsFile)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_setting_path = QtWidgets.QLabel(WindowSettingsPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_setting_path.sizePolicy().hasHeightForWidth())
        self.lbl_setting_path.setSizePolicy(sizePolicy)
        self.lbl_setting_path.setAutoFillBackground(True)
        self.lbl_setting_path.setObjectName("lbl_setting_path")
        self.horizontalLayout.addWidget(self.lbl_setting_path)
        self.btn_browse_settings = QtWidgets.QPushButton(WindowSettingsPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_browse_settings.sizePolicy().hasHeightForWidth())
        self.btn_browse_settings.setSizePolicy(sizePolicy)
        self.btn_browse_settings.setObjectName("btn_browse_settings")
        self.horizontalLayout.addWidget(self.btn_browse_settings)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.lblBackupDirectory = QtWidgets.QLabel(WindowSettingsPanel)
        self.lblBackupDirectory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblBackupDirectory.setObjectName("lblBackupDirectory")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblBackupDirectory)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_backup_path = QtWidgets.QLabel(WindowSettingsPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_backup_path.sizePolicy().hasHeightForWidth())
        self.lbl_backup_path.setSizePolicy(sizePolicy)
        self.lbl_backup_path.setAutoFillBackground(True)
        self.lbl_backup_path.setObjectName("lbl_backup_path")
        self.horizontalLayout_2.addWidget(self.lbl_backup_path)
        self.btn_browse_backup = QtWidgets.QPushButton(WindowSettingsPanel)
        self.btn_browse_backup.setObjectName("btn_browse_backup")
        self.horizontalLayout_2.addWidget(self.btn_browse_backup)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.lblLogsDirectory = QtWidgets.QLabel(WindowSettingsPanel)
        self.lblLogsDirectory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLogsDirectory.setObjectName("lblLogsDirectory")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblLogsDirectory)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_logs_path = QtWidgets.QLabel(WindowSettingsPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_logs_path.sizePolicy().hasHeightForWidth())
        self.lbl_logs_path.setSizePolicy(sizePolicy)
        self.lbl_logs_path.setAutoFillBackground(True)
        self.lbl_logs_path.setObjectName("lbl_logs_path")
        self.horizontalLayout_3.addWidget(self.lbl_logs_path)
        self.btn_browse_logs = QtWidgets.QPushButton(WindowSettingsPanel)
        self.btn_browse_logs.setObjectName("btn_browse_logs")
        self.horizontalLayout_3.addWidget(self.btn_browse_logs)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.lblLogSaving = QtWidgets.QLabel(WindowSettingsPanel)
        self.lblLogSaving.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLogSaving.setObjectName("lblLogSaving")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblLogSaving)
        self.cmb_log_saving = QtWidgets.QComboBox(WindowSettingsPanel)
        self.cmb_log_saving.setObjectName("cmb_log_saving")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmb_log_saving)
        self.lblLanguage = QtWidgets.QLabel(WindowSettingsPanel)
        self.lblLanguage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLanguage.setObjectName("lblLanguage")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblLanguage)
        self.cmb_language = QtWidgets.QComboBox(WindowSettingsPanel)
        self.cmb_language.setObjectName("cmb_language")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmb_language)
        self.lblTruthFactor = QtWidgets.QLabel(WindowSettingsPanel)
        self.lblTruthFactor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTruthFactor.setObjectName("lblTruthFactor")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblTruthFactor)
        self.tb_truth_factor = QtWidgets.QLineEdit(WindowSettingsPanel)
        self.tb_truth_factor.setText("")
        self.tb_truth_factor.setObjectName("tb_truth_factor")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tb_truth_factor)
        self.lblSquareCoeff = QtWidgets.QLabel(WindowSettingsPanel)
        self.lblSquareCoeff.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSquareCoeff.setObjectName("lblSquareCoeff")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblSquareCoeff)
        self.tb_square_coeff = QtWidgets.QLineEdit(WindowSettingsPanel)
        self.tb_square_coeff.setObjectName("tb_square_coeff")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.tb_square_coeff)
        self.lblConnStr = QtWidgets.QLabel(WindowSettingsPanel)
        self.lblConnStr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblConnStr.setObjectName("lblConnStr")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblConnStr)
        self.tb_conn_str = QtWidgets.QLineEdit(WindowSettingsPanel)
        self.tb_conn_str.setObjectName("tb_conn_str")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.tb_conn_str)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_apply = QtWidgets.QPushButton(WindowSettingsPanel)
        self.btn_apply.setObjectName("btn_apply")
        self.horizontalLayout_4.addWidget(self.btn_apply)
        self.btn_cancel = QtWidgets.QPushButton(WindowSettingsPanel)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_4.addWidget(self.btn_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)

        self.retranslateUi(WindowSettingsPanel)
        QtCore.QMetaObject.connectSlotsByName(WindowSettingsPanel)

    def retranslateUi(self, WindowSettingsPanel):
        _translate = QtCore.QCoreApplication.translate
        WindowSettingsPanel.setWindowTitle(_translate("WindowSettingsPanel", "BACS Settings"))
        self.lblSettingsFile.setText(_translate("WindowSettingsPanel", "Settings file:"))
        self.lbl_setting_path.setText(_translate("WindowSettingsPanel", "Setting_path"))
        self.btn_browse_settings.setText(_translate("WindowSettingsPanel", "Browse"))
        self.lblBackupDirectory.setText(_translate("WindowSettingsPanel", "Backup directory:"))
        self.lbl_backup_path.setText(_translate("WindowSettingsPanel", "Backup_path"))
        self.btn_browse_backup.setText(_translate("WindowSettingsPanel", "Browse"))
        self.lblLogsDirectory.setText(_translate("WindowSettingsPanel", "Logs directory:"))
        self.lbl_logs_path.setText(_translate("WindowSettingsPanel", "Logs_path"))
        self.btn_browse_logs.setText(_translate("WindowSettingsPanel", "Browse"))
        self.lblLogSaving.setText(_translate("WindowSettingsPanel", "Log saving:"))
        self.lblLanguage.setText(_translate("WindowSettingsPanel", "Language:"))
        self.lblTruthFactor.setText(_translate("WindowSettingsPanel", "Truth factor:"))
        self.lblSquareCoeff.setText(_translate("WindowSettingsPanel", "Square coefficient:"))
        self.lblConnStr.setText(_translate("WindowSettingsPanel", "Connection string:"))
        self.btn_apply.setText(_translate("WindowSettingsPanel", "Apply"))
        self.btn_cancel.setText(_translate("WindowSettingsPanel", "Cancel"))

