# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\BiometricACS\BiometricACS\APP\UI\WindowMain.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabPresenter = QtWidgets.QTabWidget(self.centralwidget)
        self.tabPresenter.setAutoFillBackground(True)
        self.tabPresenter.setObjectName("tabPresenter")
        self.tabCheckpoints = QtWidgets.QWidget()
        self.tabCheckpoints.setAutoFillBackground(True)
        self.tabCheckpoints.setObjectName("tabCheckpoints")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabCheckpoints)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter_4 = QtWidgets.QSplitter(self.tabCheckpoints)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.gbCameras = QtWidgets.QGroupBox(self.splitter_4)
        self.gbCameras.setAutoFillBackground(False)
        self.gbCameras.setObjectName("gbCameras")
        self.gridLayout = QtWidgets.QGridLayout(self.gbCameras)
        self.gridLayout.setObjectName("gridLayout")
        self.treeCameras = QtWidgets.QTreeWidget(self.gbCameras)
        self.treeCameras.setObjectName("treeCameras")
        self.treeCameras.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeCameras, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.splitter_4)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.gbVideoStream = QtWidgets.QGroupBox(self.splitter)
        self.gbVideoStream.setObjectName("gbVideoStream")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbVideoStream)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_3 = QtWidgets.QSplitter(self.gbVideoStream)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.gvFaceDetection = QtWidgets.QLabel(self.splitter_3)
        self.gvFaceDetection.setText("")
        self.gvFaceDetection.setObjectName("gvFaceDetection")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.gvLandmarksDetection = QtWidgets.QLabel(self.splitter_2)
        self.gvLandmarksDetection.setText("")
        self.gvLandmarksDetection.setObjectName("gvLandmarksDetection")
        self.gvFaceNormalization = QtWidgets.QLabel(self.splitter_2)
        self.gvFaceNormalization.setText("")
        self.gvFaceNormalization.setObjectName("gvFaceNormalization")
        self.gridLayout_3.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.lblDetectedName = QtWidgets.QLabel(self.gbVideoStream)
        self.lblDetectedName.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblDetectedName.setObjectName("lblDetectedName")
        self.gridLayout_3.addWidget(self.lblDetectedName, 1, 0, 1, 1)
        self.gbControlPanel = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbControlPanel.sizePolicy().hasHeightForWidth())
        self.gbControlPanel.setSizePolicy(sizePolicy)
        self.gbControlPanel.setMaximumSize(QtCore.QSize(16777215, 56))
        self.gbControlPanel.setObjectName("gbControlPanel")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gbControlPanel)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnGetAccess = QtWidgets.QPushButton(self.gbControlPanel)
        self.btnGetAccess.setObjectName("btnGetAccess")
        self.horizontalLayout_2.addWidget(self.btnGetAccess)
        self.btnLockCheckpoint = QtWidgets.QPushButton(self.gbControlPanel)
        self.btnLockCheckpoint.setObjectName("btnLockCheckpoint")
        self.horizontalLayout_2.addWidget(self.btnLockCheckpoint)
        self.btnUnlockCheckpoint = QtWidgets.QPushButton(self.gbControlPanel)
        self.btnUnlockCheckpoint.setObjectName("btnUnlockCheckpoint")
        self.horizontalLayout_2.addWidget(self.btnUnlockCheckpoint)
        self.gridLayout_6.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.tabPresenter.addTab(self.tabCheckpoints, "")
        self.tabSessionLog = QtWidgets.QWidget()
        self.tabSessionLog.setAutoFillBackground(True)
        self.tabSessionLog.setObjectName("tabSessionLog")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabSessionLog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lvVisitsLog = QtWidgets.QListWidget(self.tabSessionLog)
        self.lvVisitsLog.setObjectName("lvVisitsLog")
        self.gridLayout_4.addWidget(self.lvVisitsLog, 0, 0, 2, 2)
        self.tabPresenter.addTab(self.tabSessionLog, "")
        self.tabStatistics = QtWidgets.QWidget()
        self.tabStatistics.setObjectName("tabStatistics")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabStatistics)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tbSearchName = QtWidgets.QLineEdit(self.tabStatistics)
        self.tbSearchName.setObjectName("tbSearchName")
        self.gridLayout_5.addWidget(self.tbSearchName, 0, 0, 1, 1)
        self.btnSaveStatistics = QtWidgets.QPushButton(self.tabStatistics)
        self.btnSaveStatistics.setObjectName("btnSaveStatistics")
        self.gridLayout_5.addWidget(self.btnSaveStatistics, 0, 1, 1, 1)
        self.tableStatistics = QtWidgets.QTableWidget(self.tabStatistics)
        self.tableStatistics.setObjectName("tableStatistics")
        self.tableStatistics.setColumnCount(0)
        self.tableStatistics.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableStatistics, 1, 0, 1, 2)
        self.tabPresenter.addTab(self.tabStatistics, "")
        self.gridLayout_2.addWidget(self.tabPresenter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubarMain = QtWidgets.QMenuBar(MainWindow)
        self.menubarMain.setGeometry(QtCore.QRect(0, 0, 996, 21))
        self.menubarMain.setObjectName("menubarMain")
        self.mFile = QtWidgets.QMenu(self.menubarMain)
        self.mFile.setObjectName("mFile")
        self.menuExport = QtWidgets.QMenu(self.mFile)
        self.menuExport.setObjectName("menuExport")
        self.menuControl = QtWidgets.QMenu(self.menubarMain)
        self.menuControl.setObjectName("menuControl")
        self.menuSettings = QtWidgets.QMenu(self.menuControl)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAccounts = QtWidgets.QMenu(self.menuControl)
        self.menuAccounts.setObjectName("menuAccounts")
        self.menuData = QtWidgets.QMenu(self.menuControl)
        self.menuData.setObjectName("menuData")
        self.menuCheckpoints = QtWidgets.QMenu(self.menuControl)
        self.menuCheckpoints.setObjectName("menuCheckpoints")
        MainWindow.setMenuBar(self.menubarMain)
        self.statusbarCurrentEvent = QtWidgets.QStatusBar(MainWindow)
        self.statusbarCurrentEvent.setObjectName("statusbarCurrentEvent")
        MainWindow.setStatusBar(self.statusbarCurrentEvent)
        self.actionExportSessionLog = QtWidgets.QAction(MainWindow)
        self.actionExportSessionLog.setObjectName("actionExportSessionLog")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpenSettiongs = QtWidgets.QAction(MainWindow)
        self.actionOpenSettiongs.setObjectName("actionOpenSettiongs")
        self.actionImportSettings = QtWidgets.QAction(MainWindow)
        self.actionImportSettings.setObjectName("actionImportSettings")
        self.actionExportSettings = QtWidgets.QAction(MainWindow)
        self.actionExportSettings.setObjectName("actionExportSettings")
        self.actionRelogin = QtWidgets.QAction(MainWindow)
        self.actionRelogin.setObjectName("actionRelogin")
        self.actionOpenSettings = QtWidgets.QAction(MainWindow)
        self.actionOpenSettings.setObjectName("actionOpenSettings")
        self.actionExport_Accounts = QtWidgets.QAction(MainWindow)
        self.actionExport_Accounts.setObjectName("actionExport_Accounts")
        self.actionCreateAccount = QtWidgets.QAction(MainWindow)
        self.actionCreateAccount.setObjectName("actionCreateAccount")
        self.actionAddBbiometricsData = QtWidgets.QAction(MainWindow)
        self.actionAddBbiometricsData.setObjectName("actionAddBbiometricsData")
        self.actionBackingUpData = QtWidgets.QAction(MainWindow)
        self.actionBackingUpData.setObjectName("actionBackingUpData")
        self.actionAddCheckpoint = QtWidgets.QAction(MainWindow)
        self.actionAddCheckpoint.setObjectName("actionAddCheckpoint")
        self.actionAddCamera = QtWidgets.QAction(MainWindow)
        self.actionAddCamera.setObjectName("actionAddCamera")
        self.actionDeleteCamera = QtWidgets.QAction(MainWindow)
        self.actionDeleteCamera.setObjectName("actionDeleteCamera")
        self.menuExport.addAction(self.actionExportSessionLog)
        self.mFile.addAction(self.menuExport.menuAction())
        self.mFile.addSeparator()
        self.mFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionOpenSettings)
        self.menuSettings.addAction(self.actionExportSettings)
        self.menuAccounts.addAction(self.actionRelogin)
        self.menuAccounts.addAction(self.actionCreateAccount)
        self.menuAccounts.addAction(self.actionExport_Accounts)
        self.menuData.addAction(self.actionAddBbiometricsData)
        self.menuData.addAction(self.actionBackingUpData)
        self.menuCheckpoints.addAction(self.actionAddCheckpoint)
        self.menuCheckpoints.addAction(self.actionAddCamera)
        self.menuControl.addAction(self.menuData.menuAction())
        self.menuControl.addAction(self.menuCheckpoints.menuAction())
        self.menuControl.addAction(self.menuSettings.menuAction())
        self.menuControl.addAction(self.menuAccounts.menuAction())
        self.menubarMain.addAction(self.mFile.menuAction())
        self.menubarMain.addAction(self.menuControl.menuAction())

        self.retranslateUi(MainWindow)
        self.tabPresenter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnGetAccess, self.btnLockCheckpoint)
        MainWindow.setTabOrder(self.btnLockCheckpoint, self.btnUnlockCheckpoint)
        MainWindow.setTabOrder(self.btnUnlockCheckpoint, self.tabPresenter)
        MainWindow.setTabOrder(self.tabPresenter, self.lvVisitsLog)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BACS Control Panel"))
        self.gbCameras.setTitle(_translate("MainWindow", "Cameras"))
        self.gbVideoStream.setTitle(_translate("MainWindow", "Video Stream"))
        self.lblDetectedName.setText(_translate("MainWindow", "Detected Name:"))
        self.gbControlPanel.setTitle(_translate("MainWindow", "Control Panel"))
        self.btnGetAccess.setText(_translate("MainWindow", "Get Access"))
        self.btnLockCheckpoint.setText(_translate("MainWindow", "Lock Checkpoint"))
        self.btnUnlockCheckpoint.setText(_translate("MainWindow", "Unlock Checkpoint"))
        self.tabPresenter.setTabText(self.tabPresenter.indexOf(self.tabCheckpoints), _translate("MainWindow", "Сheckpoints"))
        self.tabPresenter.setTabText(self.tabPresenter.indexOf(self.tabSessionLog), _translate("MainWindow", "Session log"))
        self.btnSaveStatistics.setText(_translate("MainWindow", "Save"))
        self.tabPresenter.setTabText(self.tabPresenter.indexOf(self.tabStatistics), _translate("MainWindow", "Statistics"))
        self.mFile.setTitle(_translate("MainWindow", "File"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuControl.setTitle(_translate("MainWindow", "Control"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuAccounts.setTitle(_translate("MainWindow", "Accounts"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.menuCheckpoints.setTitle(_translate("MainWindow", "Checkpoints"))
        self.actionExportSessionLog.setText(_translate("MainWindow", "Session log"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpenSettiongs.setText(_translate("MainWindow", "Open"))
        self.actionImportSettings.setText(_translate("MainWindow", "Import"))
        self.actionExportSettings.setText(_translate("MainWindow", "Export"))
        self.actionRelogin.setText(_translate("MainWindow", "Relogin"))
        self.actionOpenSettings.setText(_translate("MainWindow", "Open"))
        self.actionExport_Accounts.setText(_translate("MainWindow", "Export Accounts"))
        self.actionCreateAccount.setText(_translate("MainWindow", "Create"))
        self.actionAddBbiometricsData.setText(_translate("MainWindow", "Add biometrics data"))
        self.actionBackingUpData.setText(_translate("MainWindow", "Backing up data"))
        self.actionAddCheckpoint.setText(_translate("MainWindow", "Add checkpoint"))
        self.actionAddCamera.setText(_translate("MainWindow", "Add camera"))
        self.actionDeleteCamera.setText(_translate("MainWindow", "Delete camera"))

